// Typed query layer over `dynamics-web-api`.
//
// `dynamics-web-api` types `select` as `string[]`, `filter` as a free `string`,
// and `expand[].property` as a free string — none of them tied to a specific
// entity. This module adds two pieces of safety on top of an authenticated
// `DynamicsWebApi` client:
//
//   * `entity<T>(dynamics, collection)` — a per-entity client that bakes in the
//     collection name and constrains `select` / `expand[].property` to `keyof T`.
//   * `filter<T>()` — an OData `$filter` builder whose field names are checked
//     against `T`, whose string values are escaped, and whose `and`/`or`
//     composition is parenthesised by construction.

import type { DynamicsWebApi } from "dynamics-web-api";

// --- filter builder ---------------------------------------------------------

/** Escapes a value for an OData string literal: `O'Brien` -> `'O''Brien'`. */
const literal = (value: string | number | boolean): string => {
    if (typeof value === "string") return `'${value.replace(/'/g, "''")}'`;
    return String(value);
};

/**
 * An immutable OData `$filter` fragment for entity `T`. Every method returns a
 * new builder; call `.toString()` (or pass it where a string is expected) to
 * get the rendered filter. Composed groups are wrapped in parentheses so
 * precedence is never ambiguous.
 */
export class FilterBuilder<T> {
    private constructor(private readonly expr: string) {}

    static create<T>(): FilterBuilder<T> {
        return new FilterBuilder<T>("");
    }

    private compare(field: keyof T & string, op: string, value: string | number | boolean): FilterBuilder<T> {
        return new FilterBuilder<T>(`${field} ${op} ${literal(value)}`);
    }

    eq(field: keyof T & string, value: string | number | boolean): FilterBuilder<T> {
        return this.compare(field, "eq", value);
    }

    ne(field: keyof T & string, value: string | number | boolean): FilterBuilder<T> {
        return this.compare(field, "ne", value);
    }

    /** Joins this fragment and `other` with `and`, parenthesising each side. */
    and(other: FilterBuilder<T>): FilterBuilder<T> {
        return new FilterBuilder<T>(`(${this.expr}) and (${other.expr})`);
    }

    /** Joins this fragment and `other` with `or`, parenthesising each side. */
    or(other: FilterBuilder<T>): FilterBuilder<T> {
        return new FilterBuilder<T>(`(${this.expr}) or (${other.expr})`);
    }

    toString(): string {
        return this.expr;
    }
}

/** Starts a typed `$filter` for entity `T`. */
export const filter = <T>(): FilterBuilder<T> => FilterBuilder.create<T>();

// --- expand option ----------------------------------------------------------

/**
 * Typed `$expand` for entity `T`. `property` must be a navigation property on
 * `T` (e.g. an entity-collection field generated by `dataverse-types-gen`).
 * The inner `select`/`filter` operate on the expanded entity, which can't be
 * inferred from `T` alone, so they stay loose strings — pair with `filter<X>()`
 * on the inner entity if you want type-checked inner filters.
 */
export interface ExpandOption<T> {
    property: keyof T & string;
    select?: string[];
    filter?: string;
    top?: number;
    orderBy?: string[];
    expand?: ExpandOption<unknown>[];
}

// --- entity client ----------------------------------------------------------

export interface RetrieveOptions<T> {
    /** Attributes to return — checked against the entity's fields. */
    select: (keyof T & string)[];
    /** A `$filter` — a typed `FilterBuilder<T>` or, as an escape hatch, a raw string. */
    filter?: FilterBuilder<T> | string;
    /** `$expand` of related records, typed so the navigation property must exist on `T`. */
    expand?: ExpandOption<T>[];
    /** `$orderby` clauses — passed through verbatim. */
    orderBy?: string[];
    /** `$top` row cap. */
    top?: number;
}

/**
 * A per-entity client. The collection name is bound once, `select` and the
 * outer `expand[].property` are typed against `T`, and reads return `T`.
 */
export interface EntityClient<T> {
    /** One page of results (whatever Dataverse returns in a single response, typically up to 5000). */
    retrieveMultiple(options: RetrieveOptions<T>): Promise<T[]>;
    /** Every matching row, following `@odata.nextLink` internally. Prefer this when the result set is bounded. */
    retrieveAll(options: RetrieveOptions<T>): Promise<T[]>;
    /** Creates a record and returns the server's representation. */
    create<R = T>(data: object): Promise<R>;
    /** PATCHes a record by primary key. */
    update(key: string, data: object): Promise<unknown>;
}

/** Builds the underlying `dynamics-web-api` request payload from `RetrieveOptions`. */
const buildRequest = <T>(collection: string, options: RetrieveOptions<T>) => ({
    collection,
    select: options.select as string[],
    filter: options.filter === undefined ? undefined : options.filter.toString(),
    expand: options.expand as { property: string; select?: string[]; filter?: string; top?: number; orderBy?: string[] }[] | undefined,
    orderBy: options.orderBy,
    top: options.top
});

/**
 * Creates a typed per-entity client over an authenticated `DynamicsWebApi`
 * instance (the one returned by `createClient`).
 */
export const entity = <T>(dynamics: DynamicsWebApi, collection: string): EntityClient<T> => ({
    retrieveMultiple: async options => {
        const result = await dynamics.retrieveMultiple<T>(buildRequest(collection, options));
        return result.value;
    },
    retrieveAll: async options => {
        const result = await dynamics.retrieveAll<T>(buildRequest(collection, options));
        return result.value;
    },
    create: <R = T>(data: object) =>
        dynamics.create<object, R>({ collection, data, returnRepresentation: true }),
    update: (key, data) => dynamics.update({ collection, key, data })
});
